export default function Reference() {
  return (
    <div>
      <h1>Welcome to the Reference Page</h1>
      <p>
      Lorem ipsum dolor sit amet. Aut officia repudiandae sit veniam eaque sit quasi enim qui animi ullam. Ex rerum quaerat 33 enim expedita et minus doloremque ab dolores rerum eos consequatur cupiditate. Eos nemo quam ut quaerat commodi sed odit deserunt et Quis minus aut sunt saepe in porro magni sit voluptatem dolor. Qui aliquid voluptate qui perferendis dolores et quidem esse. Vel perspiciatis Quis in possimus adipisci aut aliquam beatae est maxime galisum aut laborum rerum. Sed ducimus accusantium et galisum rerum rem quae voluptatibus et deserunt dolorem. Et iure quos qui quia magnam ab necessitatibus voluptas est magni aliquam aut vero dolores aut minus unde. Non alias repudiandae qui fugit velit qui assumenda porro ea laudantium possimus non dicta dolor ut laboriosam facere qui temporibus velit. Qui officia dolore aut nisi tempora aut placeat internos. </p><p>Est obcaecati dolorem id rerum ratione non quisquam galisum ut rerum maxime qui recusandae distinctio. Et nesciunt modi aut sequi perferendis qui autem cupiditate. Eum repellendus consequatur ab nostrum quam et corporis repellendus aut nisi animi ex rerum sunt est sapiente iusto ea voluptates velit? Est molestiae consequatur qui accusantium veniam nam explicabo aliquid vel molestiae facere a quia iure quo iste eaque. Qui ipsum impedit ea voluptas impedit ut laborum eius non obcaecati dolorem. Eum repellat tenetur et sunt ratione et illum reiciendis est illo quibusdam et autem labore. In labore sequi aut dolorem mollitia ut autem aperiam 33 porro aspernatur est vitae dolor et aspernatur accusantium. Sed excepturi maxime et blanditiis voluptas et quia quidem! Et ducimus optio et modi possimus id amet voluptas et voluptatem facere At quos omnis id quidem expedita et soluta fugiat. </p><p>Rem sint praesentium qui quis voluptas aut impedit galisum? Ab deserunt corrupti ea corporis mollitia est eligendi officia et libero quod et culpa laboriosam ea blanditiis facilis. In deleniti porro non aspernatur ipsum eos voluptatem rerum qui accusamus molestias qui voluptatem quas. Est deleniti voluptas sed dolorum atque aut distinctio voluptas et internos pariatur! Et harum consequatur 33 illo aperiam At numquam mollitia ab temporibus rerum id dignissimos ipsa. </p><p>At sunt perspiciatis vel autem internos et similique velit. Sit corporis similique rem galisum aliquam id aliquid omnis ex Quis reiciendis. Sed quos aspernatur aut distinctio dolor est voluptatem dolores qui temporibus minus non molestiae sequi At nihil sequi. Est amet esse et error aliquid est doloremque corporis ut vero beatae et commodi quis est atque itaque nam voluptates voluptas. In dignissimos ratione aut odit delectus est labore adipisci aut quia velit et maxime placeat est modi blanditiis. 
      </p>
    </div>
  );
}